services:
  # Backend API
  - type: web
    name: triprtrek-api
    env: python
    rootDir: backend
    buildCommand: ./build.sh
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: APP_ENV
        value: production
      - key: LOG_LEVEL
        value: INFO
      - key: CORS_ORIGINS
        value: https://triprtrek.netlify.app,http://localhost:3000
